#=================================================
# https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: ClayMoreBoy
# Github: https://github.com/ClayMoreBoy
#=================================================

name: OpenWrt-R7800-Lean(固件)

on:
# 定时触发
  schedule:
    - cron: 0 01 * * *

# Release 发布触发
#  release:
#    types: [published]

# 点赞触发
  watch:
    types: [started]

# 编辑触发
#  push:
#    branches: 
#       - master

# Config 配置触发(本项目无该配置)
#  paths:
#    - 'x86_64.config'

env:
  # 源
  REPO_URL: https://github.com/coolsnowwolf/lede
  # 分支
  REPO_BRANCH: master
  # 脚本
  DIY_SH: OpenWrt-R7800-Lean.sh
  # 释放磁盘空间
  FREE_UP_DISK: true
  # Lienol插件源
  LIENOL_PACKAGES: true
  # 开启SSH连接
  SSH_ACTIONS: false
  # Github 用户名
  GITHUB_USER_NAME: ClayMoreBoy
  # Github 邮箱
  GITHUB_USER_EMAIL: claymor3.sky@gmail.com
  # 上传分支
  UPLOAD_BRANCH: true
  # 分支
  BRANCH: R7800
  # 上传插件包
  UPLOAD_PACKAGES: true
  # 上传固件
  UPLOAD_FIRMWARE: true
  TARGET: ipq806x
  SUBTARGET: generic
  DEVICE: openwrt-ipq806x-netgear_r7800
  # 上传到中转站
  UPLOAD_TMP_LINK: true
  DOWNLOAD_URL_FILE: Tmp-Link-Url.txt
  # 编译者
  BUILD_USER: ClayMoreBoy
  # 创建+上传发布
  CREATE_RELEASE: true
  # 微信通知
  SEND_WECHAT_MSG: true
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    # 校验本地文件
    - name: Checkout
      uses: actions/checkout@master

    # 初始化编译环境
    - name: Initialize the compilation environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d
        sudo -E apt-get -qq update
        sudo apt-get -y install asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache flex g++ gawk gcc gcc-multilib gettext git git-core help2man htop lib32gcc1 libc6-dev-i386 libglib2.0-dev libncurses5-dev libssl-dev libtool libz-dev libelf-dev make msmtp ncurses-term ocaml-nox p7zip p7zip-full patch qemu-utils sharutils subversion texinfo uglifyjs unzip upx xmlto yui-compressor zlib1g-dev make cmake device-tree-compiler  g++-multilib  python3.5
        curl -fsSL https://github.com/ClayMoreBoy/dotfiles/raw/master/.bashrc >> ~/.bashrc

    # 释放磁盘空间
    - name: Free Up Disk Space
      if: env.FREE_UP_DISK == 'true'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker rmi `docker images -q`
        sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    # 克隆源代码 By bobotoy
    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>Date: %cd<br/>Commit: %s")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(date "+%Y%m%d")"
        echo "::set-env name=RELEASE_DATE::$(date "+%Y-%m-%d")"

    # 增加 PassWall 插件源 By rohu168
    - name: Update and install feeds passwall
      if: env.LIENOL_PACKAGES == 'true'
      run: |
        chmod +x passwall.sh && cp passwall.sh ./openwrt && cd openwrt && ./passwall.sh
    
    # 更新源
    - name: Update Feeds
      if: env.LIENOL_PACKAGES == 'false'
      working-directory: ./openwrt
      run:  |
        ./scripts/feeds clean
        ./scripts/feeds update -a

    # 安装源
    - name: Install Feeds
      if: env.LIENOL_PACKAGES == 'false'
      working-directory: ./openwrt
      run:  ./scripts/feeds install -a

    # 加载自定义配置文件
    - name: Load Custom Configuration
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    # SSH连接
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    # 下载软件包
    - name: Make Download
      working-directory: ./openwrt
      id: package
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    
    # 编译固件
    - name: Compile Firmware
      working-directory: ./openwrt
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"        
    
    # 上传到分支 By yfdoor
    - name: Upload Branch
      if: env.UPLOAD_BRANCH == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
          cd openwrt/bin
          git init
          git config user.name $GITHUB_USER_NAME
          git config user.email $GITHUB_USER_EMAIL
          git add .
          git commit -m "Update OpenWrt_"$BRANCH
          git push --force --quiet https://$GITHUB_TOKEN@github.com/ClayMoreBoy/OpenWrt.git HEAD:OpenWrt_$BRANCH
          
    # 上传配置 By SuLingGG
    - name: Upload Config
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: .config
        path: openwrt/.config
    
    # 上传配置 By SuLingGG
    - name: Upload Packages
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_PACKAGES == 'true'
      with:
        name: packages
        path: openwrt/bin/packages
        
    # 上传官方镜像 By SuLingGG
    - name: Upload SquashFS Factory Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: ${{ env.BUILD_USER }}-${{ env.DATE }}-${{ env.DEVICE }}-squashfs-factory.img
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-factory.img
    
    # 上传系统升级镜像 By SuLingGG
    - name: Upload SquashFS Sysupgrade Image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: ${{ env.BUILD_USER }}-${{ env.DATE }}-${{ env.DEVICE }}-squashfs-sysupgrade.bin
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-sysupgrade.bin
    
    # 上传镜像文件哈希值 By SuLingGG
    - name: Upload Images Sha256sums
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: sha256sums
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums
    
    # 上传文件到Tmp.Link By SuLingGG
    - name: Upload Firmwares To Tmp.Link
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_TMP_LINK == 'true'
      run: |
        cd openwrt/bin/packages
        zip -q -r ../targets/$TARGET/$SUBTARGET/packages.zip *
        cd ../targets/$TARGET/$SUBTARGET
        rm -f *.manifest
        rm -f *uImage
        find . -maxdepth 1 ! -name "$DOWNLOAD_URL_FILE" -type f -exec echo {} >> $DOWNLOAD_URL_FILE \; -exec curl -k -F "file=@{}" -F "token=${{ secrets.TMP_LINK_TOKEN }}" -F "model=3" -X POST "https://connect.tmp.link/api_v2/cli_uploader" -s >> $DOWNLOAD_URL_FILE \;
        sed -i 's/\.\///g' $DOWNLOAD_URL_FILE
        sed -i '/^Upload.*/d' $DOWNLOAD_URL_FILE
        sed -i '/^Thank.*/d' $DOWNLOAD_URL_FILE
        sed -i '/Download/G' $DOWNLOAD_URL_FILE
    
    # 上传下载地址文件
    - name: Upload Download Url File
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_TMP_LINK == 'true'
      with:
        name: ${{ env.DOWNLOAD_URL_FILE }}
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DOWNLOAD_URL_FILE }}
    
    # 创建发布 By ylqjgm
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_DATE }}
        release_name: Netgear R7800 🚀 | 自动编译 / ${{ env.RELEASE_DATE }}
        body: |            
            1、本固件为自动编译
            2、发行版中只提供完整的固件
            3、需要单独IPK请到分支下载
            4、源码：${{ env.REPO_URL }}
            5、分支：${{ env.REPO_BRANCH }}
            -- Build by ${{ env.BUILD_USER }} @ with Github Action on ${{ env.RELEASE_DATE }}
            -- Automated build | 自动编译
            当前使用版本:（编译前的最后一次大雕源码更新记录）
            ${{ github.event.commits[0].message }}
            ${{ env.useVersionInfo }}
        draft: false
        prerelease: false

    # 上传发布
    - name: Upload Release
      id: upload-release-asset
      uses: actions/upload-release-asset@master
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-factory.img
          asset_name: ${{ env.BUILD_USER }}-${{ env.DATE }}-${{ env.DEVICE }}-squashfs-factory.img
          asset_content_type: application/octet-stream

    # 上传发布
    - name: Upload Release
      uses: actions/upload-release-asset@master
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-sysupgrade.bin
          asset_name: ${{ env.BUILD_USER }}-${{ env.DATE }}-${{ env.DEVICE }}-squashfs-sysupgrade.bin
          asset_content_type: application/octet-stream

    # 上传发布
    - name: Upload Release
      uses: actions/upload-release-asset@master
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/.config
          asset_name: .config
          asset_content_type: application/octet-stream

    # 上传发布
    - name: Upload Release
      uses: actions/upload-release-asset@master
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/$TARGET/$SUBTARGET/packages.zip
          asset_name: Packages.zip
          asset_content_type: application/octet-stream

    # 上传发布
    - name: Upload Release
      uses: actions/upload-release-asset@master
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums
          asset_name: sha256sums
          asset_content_type: application/octet-stream

    # 微信通知 By rohu168
    - name: Sending WeChat Notification
      if: env.SEND_WECHAT_MSG == 'true' && steps.compile.outputs.status == 'success'
      uses: yakumioto/serverchan-action@v1
      with:
        key: ${{ secrets.SCKEY }}
        text: ${{ env.BRANCH }}固件编译完成！
        desp: 源码:${{ env.REPO_URL }}
